title: Girls' Games Workshop e.V.
email: mail [at] girlsgamesworkshop [dot] org
phone: 030 831 904 89
address: |-
  **Girls' Games Workshop e.V.**
  ℅ Linda Stein
  Mareschstraße 4
  12055 Berlin
executives: |- # include no newlines at end
  Linda Stein
  Glenna Lee Buford
content: |+ # include all newlines at end
  Linda Stein
  Mareschstraße 4
  12055 Berlin

# ^ newline
economy_id: 27/666/59313
register_nr: VR 37850 B

description: >-
  Girls' Games Workshop was founded in Berlin in 2015, and is a non profit organization run by volunteers.
  Join us for a one day workshop that aims to encourage girls to design and develop games.
  Participants will be introduced to game design and development in a series of interactive lectures.

baseurl: "" # needs to be defined to translate permalinks
url: "https://girlsgamesworkshop.org" # the base hostname & protocol for your site, e.g. http://example.com
author: Girls' Games Workshop e.V.

languages: ["de", "en"]
exclude_from_localizations: ["assets", "vendor"]

plugins:
  - jekyll-feed
  - jekyll-multiple-languages-plugin

sass:
  style: compressed

collections:
  menu:
    output: true
    permalink: /:title

exclude:
  - Rakefile
  - Gemfile
  - Gemfile.lock
  - README

paginate: 5
paginate_path: "/events/page:num/"
