title: Girls Games Workshop e.V.
email: mail [at] girlsgamesworkshop [dot] org
phone: "  "
address: |-
  **Girls' Games Workshop e.V.**
  Mareschstraße 4
  12055 Berlin
executives: |- # include no newlines at end
  Linda Stein
  Glenna Lee Buford
content: |+ # include all newlines at end
  Linda Stein
  Mareschstraße 4
  12055 Berlin

# ^ newline
economy_id: 27/666/59313
register_nr: VR 37850 B

description: >- # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.

baseurl: "" # needs to be defined to translate permalinks
url: "https://girlsgamesworkshop.org" # the base hostname & protocol for your site, e.g. http://example.com
author: Girls Games Workshop e.V.

languages: ["en", "de"]
exclude_from_localizations: ["assets", "vendor"]

plugins:
  - jekyll-feed
  - jekyll-multiple-languages-plugin

sass:
  style: compressed

collections:
  menu:
    output: true
    permalink: /:title

exclude:
  - Rakefile
  - Gemfile
  - Gemfile.lock
  - README

paginate: 5
paginate_path: "/events/page:num/"
